### ISSUE TITLE
message

### ISSUE THREAD

**Issue by josse7cz** [wang-boyu/agents-and-networks-in-python#5]
Hi. I am a student at the University of Hradec Králové. Can I try to extend your model to track population evacuation? Or change the map?

**Comment by wang-boyu** [comment]
Sure! Please feel free to fork the repo and change however you like.

I've added a Apache 2.0 License file in case this is your concern.

**Comment by josse7cz** [comment]
Thx. I have one more question. What all needs to be changed to change the 
map. Is there any guide? Or do you need to study OSM, mesa-geo and others.

**Comment by wang-boyu** [comment]
This is related to Mesa-Geo. Previously I created a feature request https://github.com/projectmesa/mesa-geo/issues/48 to add more basemaps but didn't have the time to implement it.

If you want a temporary solution, you may try to do some quick chances like this:

1. Fork this repo and the mesa-geo repo
2. In your forked repo, remember to change `requirements.txt` to point to your forked mesa-geo, i.e., from `mesa-geo==0.4.0` to `git+https://github.com/YOUR_USERNAME/mesa-geo.git#egg=mesa-geo `
3. In your forked mesa-geo repo, change this file that creates the OSM basemap: `mesa_geo/visualization/templates/js/MapModule.js`.
   In particular, you may need to change these lines:
   ```javascript
   // create the OSM tile layer with correct attribution
    const osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
    const osmAttrib = 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors'
    const osm = new L.TileLayer(osmUrl, {minZoom: 0, maxZoom: 18, attribution: osmAttrib})
    Lmap.addLayer(osm)
   ```
   You may also need to search how to add the map you prefer using Leaflet.js.

**Comment by wang-boyu** [comment]
Closing as it is mesa-geo specific and links to https://github.com/projectmesa/mesa-geo/issues/48.

@josse7cz pls feel free to comment here as you see fit.
